version: "3"
services:
  backend:
    build:
      context: apps/backend
      dockerfile: Dockerfile

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    env_file: .env
