version: "3"
services:
  redis:
    image: bitnami/redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - data:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  data:
