-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
CREATE OR REPLACE FUNCTION public.fn_ksuid() RETURNS text LANGUAGE 'plpgsql' COST 100 VOLATILE PARALLEL UNSAFE AS $BODY$
declare v_time timestamp with time zone := null;
v_seconds numeric := null;
v_payload bytea := null;
v_numeric numeric := null;
v_base62 text := '';
v_epoch numeric = 1400000000;
-- 2014-05-13T16:53:20Z
v_alphabet char array [62] := array [
		'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
		'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',
		'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 
		'U', 'V', 'W', 'X', 'Y', 'Z', 
		'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 
		'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
		'u', 'v', 'w', 'x', 'y', 'z'];
i integer := 0;
begin -- Get the current time
v_time := clock_timestamp();
-- Extract seconds from the current time and apply epoch
v_seconds := EXTRACT(
	EPOCH
	FROM v_time
) - v_epoch;
-- Generate a numeric value from the seconds
v_numeric := v_seconds * pow(2::numeric, 128);
-- Generate a pseudo-random payload
-- v_payload := gen_random_bytes(16); -- to be used with `pgcrypto`
v_payload := decode(
	md5(v_time::text || random()::text || random()::text),
	'hex'
);
-------------------------------------------------------------------
-- FOR TEST: the expected result is '0ujtsYcgvSTl8PAuAdqWYSMnLOv'
-------------------------------------------------------------------
-- v_numeric := 107608047 * pow(2::numeric, 128);
-- v_payload := decode('B5A1CD34B5F99D1154FB6853345C9735', 'hex');
-- Add the payload to the numeric value
while i < 16 loop i := i + 1;
v_numeric := v_numeric + (
	get_byte(v_payload, i - 1) * pow(2::numeric, (16 - i) * 8)
);
end loop;
-- Encode the numeric value to base62
while v_numeric <> 0 loop v_base62 := v_base62 || v_alphabet [mod(v_numeric, 62) + 1];
v_numeric := div(v_numeric, 62);
end loop;
v_base62 := reverse(v_base62);
v_base62 := lpad(v_base62, 27, '0');
return v_base62;
end $BODY$;
ALTER FUNCTION public.fn_ksuid() OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.fn_ksuid() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.fn_ksuid() TO anon;
GRANT EXECUTE ON FUNCTION public.fn_ksuid() TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_ksuid() TO postgres;
GRANT EXECUTE ON FUNCTION public.fn_ksuid() TO service_role;
-- ALTER TABLE IF EXISTS public.hellofresh DROP COLUMN IF EXISTS uid;
-- ALTER TABLE IF EXISTS public.hellofresh
-- 	RENAME uid TO created_at;
ALTER TABLE public.hellofresh
ALTER COLUMN created_at TYPE timestamp with time zone;
ALTER TABLE IF EXISTS public.hellofresh
ALTER COLUMN created_at
SET DEFAULT now();
ALTER TABLE IF EXISTS public.hellofresh
ALTER COLUMN created_at DROP NOT NULL;
-- ALTER TABLE IF EXISTS public.hellofresh
-- ALTER COLUMN created_at DROP IDENTITY;
ALTER TABLE IF EXISTS public.hellofresh
	RENAME uid TO id;
ALTER TABLE public.hellofresh
ALTER COLUMN id TYPE text COLLATE pg_catalog."default";
ALTER TABLE IF EXISTS public.hellofresh
ALTER COLUMN id
SET DEFAULT fn_ksuid();
ALTER TABLE IF EXISTS public.hellofresh
ALTER COLUMN id DROP IDENTITY;
ALTER TABLE IF EXISTS public.hellofresh
ALTER COLUMN id
SET STORAGE EXTENDED;
ALTER TABLE IF EXISTS public.hellofresh
	RENAME uid TO recipe;
ALTER TABLE public.hellofresh
ALTER COLUMN recipe TYPE jsonb;
ALTER TABLE IF EXISTS public.hellofresh
ALTER COLUMN recipe DROP NOT NULL;
ALTER TABLE IF EXISTS public.hellofresh
ALTER COLUMN recipe DROP IDENTITY;
ALTER TABLE IF EXISTS public.hellofresh
ALTER COLUMN recipe
SET STORAGE EXTENDED;
ALTER TABLE IF EXISTS public.hellofresh
ADD CONSTRAINT hellofresh_pkey PRIMARY KEY (id);
ALTER TABLE public.recipes
ALTER COLUMN id TYPE text COLLATE pg_catalog."default";
ALTER TABLE IF EXISTS public.recipes
ALTER COLUMN id
SET DEFAULT fn_ksuid();
ALTER TABLE IF EXISTS public.recipes
ALTER COLUMN id DROP IDENTITY;
ALTER TABLE IF EXISTS public.recipes
ALTER COLUMN id
SET STORAGE EXTENDED;