version: "2"

services:
  redis:
    image: docker.io/bitnami/redis:7.0.5
    restart: unless-stopped
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  postgresql:
    image: docker.io/bitnami/postgresql:14
    ports:
      - "5432:5432"
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"

  pgadmin:
    container_name: pgadmin4_container
    network_mode: host
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    # ports:
    #   - 8080:80

  # meilisearch:
  #   image: getmeili/meilisearch:v0.28
  #   ports:
  #     - 7700:7700
  #   environment:
  #     - MEILI_MASTER_KEY=MASTER_KEY
  #     - MEILI_ENV=development
