// Generated by https://quicktype.io

export interface Ingredients {
  take: number;
  skip: number;
  count: number;
  total: number;
  items: Item[];
}

export interface Item {
  country: string;
  id: string;
  type: string;
  name: string;
  slug: string;
  description: null | string;
  internalName: null | string;
  shipped: boolean;
  imageLink: null | string;
  imagePath: null | string;
  usage: number;
  hasDuplicatedName: null;
  allergens: Allergen[];
  family: Family | null;
  uuid: string;
}

export interface Allergen {
  id: string;
  type: string;
  description: null;
  tracesOf: boolean;
  triggersTracesOf: boolean;
  iconLink: string;
  iconPath: string;
  usage: number;
  name: string;
  slug: string;
}

export interface Family {
  id: string;
  type: string;
  description: null;
  priority: number;
  iconLink: null | string;
  iconPath: null | string;
  usageByCountry: { [key: string]: number };
  createdAt: string;
  updatedAt: string;
  uuid: string;
  name: string;
  slug: string;
}
